MaxUsernameLength = 15
MaxDisplaynameLength = 50
MinimumPasswordLength = 6

[Web]
Canon = "https://bookmarkwarrior.com/"
Host = ":9001"
SessionCookie = "Session"
SessionExpiryDays = 14
DateFormat = "January 2, 2006"

[PayPal]
OAuthAPI = "https://api.sandbox.paypal.com/v1/oauth2/token/"
OrderAPI = "https://api.sandbox.paypal.com/v2/checkout/orders/"
Client = "MYPAYPALCLIENTID"
Secret = "MYPAYPALSECRET"
OneTimeCost = 10.00
DomesticCurrency = "USD" # PayPal Currency Code
DomesticCurrencySigil = "$"

[Database]
ConnectionString = "bookmarkboy:password@tcp(localhost)/bookmarkwarrior"
DatetimeFormat = "2006-01-02 15:04:05"

# html/template dependencies
[[Templates]]
Name = "tmpl/index.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/signup-steps.html",
	"tmpl/my/welcome.html",
	"tmpl/my/welcome-sidebar.html" ]

[[Templates]]
Name = "tmpl/user.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html",
	"tmpl/my/no-bookmarks.html" ]

[[Templates]]
Name = "tmpl/login.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html" ]

[[Templates]]
Name = "tmpl/signup-new.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/signup-steps.html",
	"tmpl/my/encourage-sidebar.html" ]

[[Templates]]
Name = "tmpl/signup-create.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/signup-steps.html" ]

[[Templates]]
Name = "tmpl/signup-free.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/signup-steps.html" ]

[[Templates]]
Name = "tmpl/signup-receipt.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/signup-steps.html",
	"tmpl/header.html" ]

[[Templates]]
Name = "tmpl/user-add.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html" ]

[[Templates]]
Name = "tmpl/user-archive.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html",
	"tmpl/my/no-archived.html" ]

[[Templates]]
Name = "tmpl/user-edit.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html" ]

[[Templates]]
Name = "tmpl/user-settings.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html" ]

[[Templates]]
Name = "tmpl/user-change-password.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html" ]

[[Templates]]
Name = "tmpl/user-change-name.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html" ]

[[Templates]]
Name = "tmpl/user-derez.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/user-aside.html" ]

[[Templates]]
Name = "tmpl/privacy.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/my/welcome-sidebar.html",
	"tmpl/my/info-privacy.html" ]

[[Templates]]
Name = "tmpl/about.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/my/welcome-sidebar.html",
	"tmpl/my/info-about.html" ]

[[Templates]]
Name = "tmpl/technology.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/my/welcome-sidebar.html",
	"tmpl/my/info-technology.html" ]

[[Templates]]
Name = "tmpl/mission.html"
Dependencies = [ "tmpl/head.html",
	"tmpl/footer.html",
	"tmpl/header.html",
	"tmpl/my/welcome-sidebar.html",
	"tmpl/my/info-mission.html" ]
